### ISSUE TITLE
Upgrade to latest Spring Boot version and Log4J2

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/circus-train#4]
This is a pre-step to fix #3

**Comment by massdosage** [comment]
Due to various version incompatibilities between different versions of Hadoop, Hive, Log4J, slf4j, Spring and Log4J2 we have decided to stick with Log4J and an older version of Spring Boot that still supports it. If at the future we have a requirement to upgrade the Spring Boot version we can revisit what logging framework we decide to use and at that point we might need to drop support for older versions of Hive that have the slf4j-log4j jar high on their classpath.
